---
title: "naive-bayes-recorddata"
author: "Ramdayal Rewaria"
date: "2022-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(tidyverse)
library(dplyr)
library(caret)
library(e1071)
library(caTools)
library(yardstick)
library(naivebayes)
library(ggplot2)
library(psych)
library(sjPlot)
library(klaR)
```

```{r}
df = read_csv("../../data/01-modified-data/data_cleaned.csv")
head(df)
```

```{r}
barplot(table(df$label), col = 'lightblue', main = 'Distribution of Labels', xlab = 'Labels', ylab = 'Count')

```

```{r}
plot(df$cumulative_points, df$win_history, col = 'lightblue', main = 'Points vs Win History', xlab = 'Cumulative Points', ylab = 'Win History')
```

```{r}
a = factor(df$status, levels = unique(df$status))
df$status = as.integer(a)
```

```{r}
a = factor(df$constructorRef, levels = unique(df$constructorRef))
df$constructorRef = as.integer(a)
```

```{r}
a = factor(df$weather, levels = unique(df$weather))
df$weather = as.integer(a)
```

```{r}
a = factor(df$stop, levels = unique(df$stop))
df$stop = as.integer(a)
```

```{r}
a = factor(df$label, levels = unique(df$label))
df$label = as.integer(a)
```

```{r}
df = df[-c(1:3)]
```

```{r}
df$label = as.factor(df$label)
df
```

```{r}
set.seed(1973)

sample <- sample(c(TRUE, FALSE), nrow(df), replace=TRUE, prob=c(0.8,0.2))
train  <- df[sample, ]
test   <- df[!sample, ]
```


```{r}
nrow(train)
nrow(test)
```

```{r}
set.seed(1973)
model1=NaiveBayes(label ~., data=train)
model = naive_bayes(label ~., data=train)
```

```{r}
plot(model1)
```

```{r}
train_pred=predict(model,train)
train_cm = table(train_pred,train$label)
confusionMatrix(train_cm)
```

```{r}
test_pred=predict(model,test)
test_cm = table(test_pred,test$label)
confusionMatrix(test_cm)
```

```{r}
train_cm_df = data.frame(train_cm)
colnames(train_cm_df) = c('pred', 'truth', 'y')

ggplot(data = train_cm_df, mapping = aes(x = truth , y = pred)) +
  geom_tile(aes(fill = y), colour = "white") +
  labs(title = 'Confusion Matrix of Train Data') +
  scale_x_discrete(labels=c("1" = "Podium", "2" = "Top_10", "3" = "Outide_Top_10")) +
  scale_y_discrete(labels=c("1" = "Podium", "2" = "Top_10", "3" = "Outide_Top_10")) +
  geom_text(aes(label = sprintf("%1.0f", y)), vjust = 1, colour = 'white') +
  #scale_fill_gradient(low = "lightblue", high = "yellow") +
  theme_bw() + theme(legend.position = "none")
```

```{r}
test_cm_df = data.frame(test_cm)
colnames(test_cm_df) = c('pred', 'truth', 'y')

ggplot(data = test_cm_df, mapping = aes(x = truth , y = pred)) +
  geom_tile(aes(fill = y), colour = "white") +
  labs(title = 'Confusion Matrix of Test Data') +
  scale_x_discrete(labels=c("1" = "Podium", "2" = "Top_10", "3" = "Outide_Top_10")) +
  scale_y_discrete(labels=c("1" = "Podium", "2" = "Top_10", "3" = "Outide_Top_10")) +
  geom_text(aes(label = sprintf("%1.0f", y)), vjust = 1, colour = 'white') +
  # scale_fill_gradient(low = "cyan", high = "darkgoldenrod1") +
  theme_bw() + theme(legend.position = "none")
```

```{r}
model1
```
